In [1]:
import pandas as pd 
import numpy as np
import os 
# from image_processing.image_processing import construct_image_dataframe
from image_processing import extracting_labels

In [2]:
# create instances for loading data
mobile_image_dir = "D:\\Machine_Learning\\Portfolio_Project_Machine_Learning\\Mobile_Phone_Recognition\\mobile_phone_images\\mobile_images"
mobile_labels_dir = "D:\\Machine_Learning\\Portfolio_Project_Machine_Learning\\Mobile_Phone_Recognition\\image_processing\\mobile_labels.txt"

In [3]:
img_dir = "D:\\Machine_Learning\\Portfolio_Project_Machine_Learning\\Mobile_Phone_Recognition\\mobile_phone_images\\mobile_images"

In [4]:
# extract images and labels from resources 
# images_list = os.listdir(mobile_image_dir)
# images_ar = np.array(images_list)
label_ar = extracting_labels(mobile_labels_dir)

In [ ]:
# Get all image filenames
image_files = os.listdir(img_dir)

# Sort the filenames numerically based on the number in the filename
image_files.sort(key=lambda x: int(x.split('_')[1].split('.')[0]))
images_ar = np.array(image_files)

In [6]:
print(f"Labels:{label_ar[:5]}\n")
print(f"Images: {images_ar[:5]}")

Labels:['Samsung SM-A556B Galaxy A55 5G Dual SIM 8GB 128GB Awesome Lemon EU\n'
 'Xiaomi 14 Ultra 5G 16GB/512GB White (White) Dual SIM\n'
 'Samsung Galaxy S22+ 5G 8GB/128GB Black (Phantom Black) Dual SIM SM-S906\n'
 'Samsung Galaxy A55 Smartphone 128GB 5G Midnight Blue\n'
 'Samsung Galaxy A03 Smartphone 64GB, 4GB RAM, Dual SIM, Blue\n']

Images: ['image_4.jpg' 'image_5.jpg' 'image_6.jpg' 'image_7.jpg' 'image_8.jpg']

Image Processing: Approach

+ Renaming the images in the folder 
+ Data Transformation
+ Data Cleaning

## Renaming images in the folder

+ rename the filename of the image
+ check if images has other extensions: jpeg, png, jpg, etc.

In [7]:
# check the extensions of images 
extensions = ('.png', '.jpg', '.jpeg', '.bmp', '.gif')
png, jpg, jpeg, bmp, gif = np.zeros(len(extensions))

In [8]:
# Assuming images_list is defined
for image_file in image_files:
    if image_file.endswith(extensions[0]):
        png += 1
    elif image_file.endswith(extensions[1]):
        jpg += 1
    elif image_file.endswith(extensions[2]):
        jpeg += 1
    elif image_file.endswith(extensions[3]):
        bmp += 1
    elif image_file.endswith(extensions[4]):
        gif += 1

# Display results
print("PNG files:", png)
print("JPG files:", jpg)
print("JPEG files:", jpeg)
print("BMP files:", bmp)
print("GIF files:", gif)

PNG files: 0.0
JPG files: 802.0
JPEG files: 0.0
BMP files: 0.0
GIF files: 0.0

In [9]:
new_names = [f"smartphone_{count}.jpg" for count in range(len(image_files))]

# Loop through the image files and rename them
for old_name, new_name in zip(image_files, new_names):
    old_path = os.path.join(img_dir, old_name)
    new_path = os.path.join(img_dir, new_name)

    # Check if the new file already exists
    if not os.path.exists(new_path):    
        os.rename(old_path, new_path)  # Rename file
        print(f"Renamed {old_name} to {new_name}")
    else:
        print(f"Skipping renaming: {new_name} already exists")

Renamed image_4.jpg to smartphone_0.jpg
Renamed image_5.jpg to smartphone_1.jpg
Renamed image_6.jpg to smartphone_2.jpg
Renamed image_7.jpg to smartphone_3.jpg
Renamed image_8.jpg to smartphone_4.jpg
Renamed image_9.jpg to smartphone_5.jpg
Renamed image_10.jpg to smartphone_6.jpg
Renamed image_11.jpg to smartphone_7.jpg
Renamed image_12.jpg to smartphone_8.jpg
Renamed image_13.jpg to smartphone_9.jpg
Renamed image_14.jpg to smartphone_10.jpg
Renamed image_15.jpg to smartphone_11.jpg
Renamed image_16.jpg to smartphone_12.jpg
Renamed image_17.jpg to smartphone_13.jpg
Renamed image_18.jpg to smartphone_14.jpg
Renamed image_19.jpg to smartphone_15.jpg
Renamed image_20.jpg to smartphone_16.jpg
Renamed image_21.jpg to smartphone_17.jpg
Renamed image_22.jpg to smartphone_18.jpg
Renamed image_23.jpg to smartphone_19.jpg
Renamed image_24.jpg to smartphone_20.jpg
Renamed image_25.jpg to smartphone_21.jpg
Renamed image_26.jpg to smartphone_22.jpg
Renamed image_27.jpg to smartphone_23.jpg
Renamed image_31.jpg to smartphone_24.jpg
Renamed image_32.jpg to smartphone_25.jpg
Renamed image_33.jpg to smartphone_26.jpg
Renamed image_34.jpg to smartphone_27.jpg
Renamed image_35.jpg to smartphone_28.jpg
Renamed image_36.jpg to smartphone_29.jpg
Renamed image_37.jpg to smartphone_30.jpg
Renamed image_38.jpg to smartphone_31.jpg
Renamed image_39.jpg to smartphone_32.jpg
Renamed image_40.jpg to smartphone_33.jpg
Renamed image_41.jpg to smartphone_34.jpg
Renamed image_42.jpg to smartphone_35.jpg
Renamed image_43.jpg to smartphone_36.jpg
Renamed image_44.jpg to smartphone_37.jpg
Renamed image_45.jpg to smartphone_38.jpg
Renamed image_46.jpg to smartphone_39.jpg
Renamed image_47.jpg to smartphone_40.jpg
Renamed image_48.jpg to smartphone_41.jpg
Renamed image_49.jpg to smartphone_42.jpg
Renamed image_50.jpg to smartphone_43.jpg
Renamed image_51.jpg to smartphone_44.jpg
Renamed image_52.jpg to smartphone_45.jpg
Renamed image_53.jpg to smartphone_46.jpg
Renamed image_54.jpg to smartphone_47.jpg
Renamed image_58.jpg to smartphone_48.jpg
Renamed image_59.jpg to smartphone_49.jpg
Renamed image_60.jpg to smartphone_50.jpg
Renamed image_61.jpg to smartphone_51.jpg
Renamed image_62.jpg to smartphone_52.jpg
Renamed image_63.jpg to smartphone_53.jpg
Renamed image_64.jpg to smartphone_54.jpg
Renamed image_65.jpg to smartphone_55.jpg
Renamed image_66.jpg to smartphone_56.jpg
Renamed image_67.jpg to smartphone_57.jpg
Renamed image_68.jpg to smartphone_58.jpg
Renamed image_69.jpg to smartphone_59.jpg
Renamed image_70.jpg to smartphone_60.jpg
Renamed image_71.jpg to smartphone_61.jpg
Renamed image_72.jpg to smartphone_62.jpg
Renamed image_73.jpg to smartphone_63.jpg
Renamed image_74.jpg to smartphone_64.jpg
Renamed image_75.jpg to smartphone_65.jpg
Renamed image_76.jpg to smartphone_66.jpg
Renamed image_77.jpg to smartphone_67.jpg
Renamed image_78.jpg to smartphone_68.jpg
Renamed image_79.jpg to smartphone_69.jpg
Renamed image_80.jpg to smartphone_70.jpg
Renamed image_81.jpg to smartphone_71.jpg
Renamed image_85.jpg to smartphone_72.jpg
Renamed image_86.jpg to smartphone_73.jpg
Renamed image_87.jpg to smartphone_74.jpg
Renamed image_88.jpg to smartphone_75.jpg
Renamed image_89.jpg to smartphone_76.jpg
Renamed image_90.jpg to smartphone_77.jpg
Renamed image_91.jpg to smartphone_78.jpg
Renamed image_92.jpg to smartphone_79.jpg
Renamed image_93.jpg to smartphone_80.jpg
Renamed image_94.jpg to smartphone_81.jpg
Renamed image_95.jpg to smartphone_82.jpg
Renamed image_96.jpg to smartphone_83.jpg
Renamed image_97.jpg to smartphone_84.jpg
Renamed image_98.jpg to smartphone_85.jpg
Renamed image_99.jpg to smartphone_86.jpg
Renamed image_100.jpg to smartphone_87.jpg
Renamed image_101.jpg to smartphone_88.jpg
Renamed image_102.jpg to smartphone_89.jpg
Renamed image_103.jpg to smartphone_90.jpg
Renamed image_104.jpg to smartphone_91.jpg
Renamed image_105.jpg to smartphone_92.jpg
Renamed image_106.jpg to smartphone_93.jpg
Renamed image_107.jpg to smartphone_94.jpg
Renamed image_108.jpg to smartphone_95.jpg
Renamed image_112.jpg to smartphone_96.jpg
Renamed image_113.jpg to smartphone_97.jpg
Renamed image_114.jpg to smartphone_98.jpg
Renamed image_115.jpg to smartphone_99.jpg
Renamed image_116.jpg to smartphone_100.jpg
Renamed image_117.jpg to smartphone_101.jpg
Renamed image_118.jpg to smartphone_102.jpg
Renamed image_119.jpg to smartphone_103.jpg
Renamed image_120.jpg to smartphone_104.jpg
Renamed image_121.jpg to smartphone_105.jpg
Renamed image_122.jpg to smartphone_106.jpg
Renamed image_123.jpg to smartphone_107.jpg
Renamed image_124.jpg to smartphone_108.jpg
Renamed image_125.jpg to smartphone_109.jpg
Renamed image_126.jpg to smartphone_110.jpg
Renamed image_127.jpg to smartphone_111.jpg
Renamed image_128.jpg to smartphone_112.jpg
Renamed image_129.jpg to smartphone_113.jpg
Renamed image_130.jpg to smartphone_114.jpg
Renamed image_131.jpg to smartphone_115.jpg
Renamed image_132.jpg to smartphone_116.jpg
Renamed image_133.jpg to smartphone_117.jpg
Renamed image_134.jpg to smartphone_118.jpg
Renamed image_135.jpg to smartphone_119.jpg
Renamed image_139.jpg to smartphone_120.jpg
Renamed image_140.jpg to smartphone_121.jpg
Renamed image_141.jpg to smartphone_122.jpg
Renamed image_142.jpg to smartphone_123.jpg
Renamed image_143.jpg to smartphone_124.jpg
Renamed image_147.jpg to smartphone_125.jpg
Renamed image_148.jpg to smartphone_126.jpg
Renamed image_149.jpg to smartphone_127.jpg
Renamed image_153.jpg to smartphone_128.jpg
Renamed image_154.jpg to smartphone_129.jpg
Renamed image_158.jpg to smartphone_130.jpg
Renamed image_159.jpg to smartphone_131.jpg
Renamed image_160.jpg to smartphone_132.jpg
Renamed image_161.jpg to smartphone_133.jpg
Renamed image_162.jpg to smartphone_134.jpg
Renamed image_163.jpg to smartphone_135.jpg
Renamed image_164.jpg to smartphone_136.jpg
Renamed image_165.jpg to smartphone_137.jpg
Renamed image_166.jpg to smartphone_138.jpg
Renamed image_167.jpg to smartphone_139.jpg
Renamed image_168.jpg to smartphone_140.jpg
Renamed image_169.jpg to smartphone_141.jpg
Renamed image_170.jpg to smartphone_142.jpg
Renamed image_171.jpg to smartphone_143.jpg
Renamed image_173.jpg to smartphone_144.jpg
Renamed image_177.jpg to smartphone_145.jpg
Renamed image_178.jpg to smartphone_146.jpg
Renamed image_179.jpg to smartphone_147.jpg
Renamed image_180.jpg to smartphone_148.jpg
Renamed image_184.jpg to smartphone_149.jpg
Renamed image_188.jpg to smartphone_150.jpg
Renamed image_189.jpg to smartphone_151.jpg
Renamed image_190.jpg to smartphone_152.jpg
Renamed image_191.jpg to smartphone_153.jpg
Renamed image_192.jpg to smartphone_154.jpg
Renamed image_193.jpg to smartphone_155.jpg
Renamed image_194.jpg to smartphone_156.jpg
Renamed image_195.jpg to smartphone_157.jpg
Renamed image_196.jpg to smartphone_158.jpg
Renamed image_197.jpg to smartphone_159.jpg
Renamed image_198.jpg to smartphone_160.jpg
Renamed image_199.jpg to smartphone_161.jpg
Renamed image_200.jpg to smartphone_162.jpg
Renamed image_201.jpg to smartphone_163.jpg
Renamed image_202.jpg to smartphone_164.jpg
Renamed image_203.jpg to smartphone_165.jpg
Renamed image_204.jpg to smartphone_166.jpg
Renamed image_208.jpg to smartphone_167.jpg
Renamed image_209.jpg to smartphone_168.jpg
Renamed image_210.jpg to smartphone_169.jpg
Renamed image_211.jpg to smartphone_170.jpg
Renamed image_212.jpg to smartphone_171.jpg
Renamed image_213.jpg to smartphone_172.jpg
Renamed image_214.jpg to smartphone_173.jpg
Renamed image_215.jpg to smartphone_174.jpg
Renamed image_216.jpg to smartphone_175.jpg
Renamed image_217.jpg to smartphone_176.jpg
Renamed image_218.jpg to smartphone_177.jpg
Renamed image_219.jpg to smartphone_178.jpg
Renamed image_220.jpg to smartphone_179.jpg
Renamed image_224.jpg to smartphone_180.jpg
Renamed image_225.jpg to smartphone_181.jpg
Renamed image_229.jpg to smartphone_182.jpg
Renamed image_230.jpg to smartphone_183.jpg
Renamed image_231.jpg to smartphone_184.jpg
Renamed image_232.jpg to smartphone_185.jpg
Renamed image_233.jpg to smartphone_186.jpg
Renamed image_234.jpg to smartphone_187.jpg
Renamed image_235.jpg to smartphone_188.jpg
Renamed image_236.jpg to smartphone_189.jpg
Renamed image_237.jpg to smartphone_190.jpg
Renamed image_241.jpg to smartphone_191.jpg
Renamed image_242.jpg to smartphone_192.jpg
Renamed image_243.jpg to smartphone_193.jpg
Renamed image_244.jpg to smartphone_194.jpg
Renamed image_245.jpg to smartphone_195.jpg
Renamed image_246.jpg to smartphone_196.jpg
Renamed image_247.jpg to smartphone_197.jpg
Renamed image_248.jpg to smartphone_198.jpg
Renamed image_249.jpg to smartphone_199.jpg
Renamed image_250.jpg to smartphone_200.jpg
Renamed image_251.jpg to smartphone_201.jpg
Renamed image_252.jpg to smartphone_202.jpg
Renamed image_253.jpg to smartphone_203.jpg
Renamed image_254.jpg to smartphone_204.jpg
Renamed image_255.jpg to smartphone_205.jpg
Renamed image_256.jpg to smartphone_206.jpg
Renamed image_257.jpg to smartphone_207.jpg
Renamed image_258.jpg to smartphone_208.jpg
Renamed image_259.jpg to smartphone_209.jpg
Renamed image_260.jpg to smartphone_210.jpg
Renamed image_261.jpg to smartphone_211.jpg
Renamed image_262.jpg to smartphone_212.jpg
Renamed image_263.jpg to smartphone_213.jpg
Renamed image_264.jpg to smartphone_214.jpg
Renamed image_268.jpg to smartphone_215.jpg
Renamed image_269.jpg to smartphone_216.jpg
Renamed image_270.jpg to smartphone_217.jpg
Renamed image_271.jpg to smartphone_218.jpg
Renamed image_272.jpg to smartphone_219.jpg
Renamed image_273.jpg to smartphone_220.jpg
Renamed image_274.jpg to smartphone_221.jpg
Renamed image_275.jpg to smartphone_222.jpg
Renamed image_276.jpg to smartphone_223.jpg
Renamed image_280.jpg to smartphone_224.jpg
Renamed image_281.jpg to smartphone_225.jpg
Renamed image_282.jpg to smartphone_226.jpg
Renamed image_283.jpg to smartphone_227.jpg
Renamed image_284.jpg to smartphone_228.jpg
Renamed image_285.jpg to smartphone_229.jpg
Renamed image_286.jpg to smartphone_230.jpg
Renamed image_287.jpg to smartphone_231.jpg
Renamed image_288.jpg to smartphone_232.jpg
Renamed image_289.jpg to smartphone_233.jpg
Renamed image_290.jpg to smartphone_234.jpg
Renamed image_291.jpg to smartphone_235.jpg
Renamed image_292.jpg to smartphone_236.jpg
Renamed image_293.jpg to smartphone_237.jpg
Renamed image_294.jpg to smartphone_238.jpg
Renamed image_295.jpg to smartphone_239.jpg
Renamed image_296.jpg to smartphone_240.jpg
Renamed image_297.jpg to smartphone_241.jpg
Renamed image_298.jpg to smartphone_242.jpg
Renamed image_299.jpg to smartphone_243.jpg
Renamed image_300.jpg to smartphone_244.jpg
Renamed image_301.jpg to smartphone_245.jpg
Renamed image_302.jpg to smartphone_246.jpg
Renamed image_303.jpg to smartphone_247.jpg
Renamed image_307.jpg to smartphone_248.jpg
Renamed image_308.jpg to smartphone_249.jpg
Renamed image_309.jpg to smartphone_250.jpg
Renamed image_310.jpg to smartphone_251.jpg
Renamed image_311.jpg to smartphone_252.jpg
Renamed image_312.jpg to smartphone_253.jpg
Renamed image_313.jpg to smartphone_254.jpg
Renamed image_314.jpg to smartphone_255.jpg
Renamed image_315.jpg to smartphone_256.jpg
Renamed image_316.jpg to smartphone_257.jpg
Renamed image_317.jpg to smartphone_258.jpg
Renamed image_318.jpg to smartphone_259.jpg
Renamed image_319.jpg to smartphone_260.jpg
Renamed image_320.jpg to smartphone_261.jpg
Renamed image_321.jpg to smartphone_262.jpg
Renamed image_322.jpg to smartphone_263.jpg
Renamed image_323.jpg to smartphone_264.jpg
Renamed image_324.jpg to smartphone_265.jpg
Renamed image_325.jpg to smartphone_266.jpg
Renamed image_326.jpg to smartphone_267.jpg
Renamed image_327.jpg to smartphone_268.jpg
Renamed image_328.jpg to smartphone_269.jpg
Renamed image_329.jpg to smartphone_270.jpg
Renamed image_330.jpg to smartphone_271.jpg
Renamed image_334.jpg to smartphone_272.jpg
Renamed image_338.jpg to smartphone_273.jpg
Renamed image_339.jpg to smartphone_274.jpg
Renamed image_340.jpg to smartphone_275.jpg
Renamed image_341.jpg to smartphone_276.jpg
Renamed image_345.jpg to smartphone_277.jpg
Renamed image_346.jpg to smartphone_278.jpg
Renamed image_350.jpg to smartphone_279.jpg
Renamed image_351.jpg to smartphone_280.jpg
Renamed image_355.jpg to smartphone_281.jpg
Renamed image_356.jpg to smartphone_282.jpg
Renamed image_357.jpg to smartphone_283.jpg
Renamed image_358.jpg to smartphone_284.jpg
Renamed image_359.jpg to smartphone_285.jpg
Renamed image_363.jpg to smartphone_286.jpg
Renamed image_364.jpg to smartphone_287.jpg
Renamed image_365.jpg to smartphone_288.jpg
Renamed image_369.jpg to smartphone_289.jpg
Renamed image_370.jpg to smartphone_290.jpg
Renamed image_371.jpg to smartphone_291.jpg
Renamed image_372.jpg to smartphone_292.jpg
Renamed image_373.jpg to smartphone_293.jpg
Renamed image_374.jpg to smartphone_294.jpg
Renamed image_375.jpg to smartphone_295.jpg
Renamed image_376.jpg to smartphone_296.jpg
Renamed image_377.jpg to smartphone_297.jpg
Renamed image_378.jpg to smartphone_298.jpg
Renamed image_379.jpg to smartphone_299.jpg
Renamed image_380.jpg to smartphone_300.jpg
Renamed image_381.jpg to smartphone_301.jpg
Renamed image_382.jpg to smartphone_302.jpg
Renamed image_383.jpg to smartphone_303.jpg
Renamed image_384.jpg to smartphone_304.jpg
Renamed image_385.jpg to smartphone_305.jpg
Renamed image_386.jpg to smartphone_306.jpg
Renamed image_387.jpg to smartphone_307.jpg
Renamed image_388.jpg to smartphone_308.jpg
Renamed image_389.jpg to smartphone_309.jpg
Renamed image_390.jpg to smartphone_310.jpg
Renamed image_391.jpg to smartphone_311.jpg
Renamed image_392.jpg to smartphone_312.jpg
Renamed image_396.jpg to smartphone_313.jpg
Renamed image_400.jpg to smartphone_314.jpg
Renamed image_401.jpg to smartphone_315.jpg
Renamed image_402.jpg to smartphone_316.jpg
Renamed image_403.jpg to smartphone_317.jpg
Renamed image_404.jpg to smartphone_318.jpg
Renamed image_405.jpg to smartphone_319.jpg
Renamed image_406.jpg to smartphone_320.jpg
Renamed image_407.jpg to smartphone_321.jpg
Renamed image_408.jpg to smartphone_322.jpg
Renamed image_409.jpg to smartphone_323.jpg
Renamed image_410.jpg to smartphone_324.jpg
Renamed image_411.jpg to smartphone_325.jpg
Renamed image_412.jpg to smartphone_326.jpg
Renamed image_413.jpg to smartphone_327.jpg
Renamed image_414.jpg to smartphone_328.jpg
Renamed image_415.jpg to smartphone_329.jpg
Renamed image_419.jpg to smartphone_330.jpg
Renamed image_420.jpg to smartphone_331.jpg
Renamed image_421.jpg to smartphone_332.jpg
Renamed image_422.jpg to smartphone_333.jpg
Renamed image_423.jpg to smartphone_334.jpg
Renamed image_427.jpg to smartphone_335.jpg
Renamed image_428.jpg to smartphone_336.jpg
Renamed image_429.jpg to smartphone_337.jpg
Renamed image_430.jpg to smartphone_338.jpg
Renamed image_431.jpg to smartphone_339.jpg
Renamed image_432.jpg to smartphone_340.jpg
Renamed image_433.jpg to smartphone_341.jpg
Renamed image_434.jpg to smartphone_342.jpg
Renamed image_435.jpg to smartphone_343.jpg
Renamed image_436.jpg to smartphone_344.jpg
Renamed image_437.jpg to smartphone_345.jpg
Renamed image_438.jpg to smartphone_346.jpg
Renamed image_439.jpg to smartphone_347.jpg
Renamed image_440.jpg to smartphone_348.jpg
Renamed image_441.jpg to smartphone_349.jpg
Renamed image_442.jpg to smartphone_350.jpg
Renamed image_443.jpg to smartphone_351.jpg
Renamed image_444.jpg to smartphone_352.jpg
Renamed image_445.jpg to smartphone_353.jpg
Renamed image_446.jpg to smartphone_354.jpg
Renamed image_447.jpg to smartphone_355.jpg
Renamed image_448.jpg to smartphone_356.jpg
Renamed image_449.jpg to smartphone_357.jpg
Renamed image_450.jpg to smartphone_358.jpg
Renamed image_454.jpg to smartphone_359.jpg
Renamed image_455.jpg to smartphone_360.jpg
Renamed image_456.jpg to smartphone_361.jpg
Renamed image_457.jpg to smartphone_362.jpg
Renamed image_458.jpg to smartphone_363.jpg
Renamed image_459.jpg to smartphone_364.jpg
Renamed image_460.jpg to smartphone_365.jpg
Renamed image_461.jpg to smartphone_366.jpg
Renamed image_462.jpg to smartphone_367.jpg
Renamed image_463.jpg to smartphone_368.jpg
Renamed image_464.jpg to smartphone_369.jpg
Renamed image_465.jpg to smartphone_370.jpg
Renamed image_466.jpg to smartphone_371.jpg
Renamed image_467.jpg to smartphone_372.jpg
Renamed image_468.jpg to smartphone_373.jpg
Renamed image_469.jpg to smartphone_374.jpg
Renamed image_470.jpg to smartphone_375.jpg
Renamed image_471.jpg to smartphone_376.jpg
Renamed image_472.jpg to smartphone_377.jpg
Renamed image_473.jpg to smartphone_378.jpg
Renamed image_474.jpg to smartphone_379.jpg
Renamed image_475.jpg to smartphone_380.jpg
Renamed image_476.jpg to smartphone_381.jpg
Renamed image_477.jpg to smartphone_382.jpg
Renamed image_481.jpg to smartphone_383.jpg
Renamed image_482.jpg to smartphone_384.jpg
Renamed image_483.jpg to smartphone_385.jpg
Renamed image_484.jpg to smartphone_386.jpg
Renamed image_485.jpg to smartphone_387.jpg
Renamed image_486.jpg to smartphone_388.jpg
Renamed image_487.jpg to smartphone_389.jpg
Renamed image_488.jpg to smartphone_390.jpg
Renamed image_489.jpg to smartphone_391.jpg
Renamed image_490.jpg to smartphone_392.jpg
Renamed image_491.jpg to smartphone_393.jpg
Renamed image_492.jpg to smartphone_394.jpg
Renamed image_493.jpg to smartphone_395.jpg
Renamed image_494.jpg to smartphone_396.jpg
Renamed image_495.jpg to smartphone_397.jpg
Renamed image_496.jpg to smartphone_398.jpg
Renamed image_497.jpg to smartphone_399.jpg
Renamed image_498.jpg to smartphone_400.jpg
Renamed image_499.jpg to smartphone_401.jpg
Renamed image_500.jpg to smartphone_402.jpg
Renamed image_501.jpg to smartphone_403.jpg
Renamed image_502.jpg to smartphone_404.jpg
Renamed image_503.jpg to smartphone_405.jpg
Renamed image_504.jpg to smartphone_406.jpg
Renamed image_508.jpg to smartphone_407.jpg
Renamed image_509.jpg to smartphone_408.jpg
Renamed image_510.jpg to smartphone_409.jpg
Renamed image_511.jpg to smartphone_410.jpg
Renamed image_512.jpg to smartphone_411.jpg
Renamed image_513.jpg to smartphone_412.jpg
Renamed image_514.jpg to smartphone_413.jpg
Renamed image_515.jpg to smartphone_414.jpg
Renamed image_516.jpg to smartphone_415.jpg
Renamed image_517.jpg to smartphone_416.jpg
Renamed image_518.jpg to smartphone_417.jpg
Renamed image_519.jpg to smartphone_418.jpg
Renamed image_520.jpg to smartphone_419.jpg
Renamed image_521.jpg to smartphone_420.jpg
Renamed image_522.jpg to smartphone_421.jpg
Renamed image_523.jpg to smartphone_422.jpg
Renamed image_524.jpg to smartphone_423.jpg
Renamed image_525.jpg to smartphone_424.jpg
Renamed image_526.jpg to smartphone_425.jpg
Renamed image_527.jpg to smartphone_426.jpg
Renamed image_528.jpg to smartphone_427.jpg
Renamed image_529.jpg to smartphone_428.jpg
Renamed image_530.jpg to smartphone_429.jpg
Renamed image_531.jpg to smartphone_430.jpg
Renamed image_535.jpg to smartphone_431.jpg
Renamed image_536.jpg to smartphone_432.jpg
Renamed image_537.jpg to smartphone_433.jpg
Renamed image_538.jpg to smartphone_434.jpg
Renamed image_539.jpg to smartphone_435.jpg
Renamed image_540.jpg to smartphone_436.jpg
Renamed image_541.jpg to smartphone_437.jpg
Renamed image_542.jpg to smartphone_438.jpg
Renamed image_543.jpg to smartphone_439.jpg
Renamed image_544.jpg to smartphone_440.jpg
Renamed image_545.jpg to smartphone_441.jpg
Renamed image_546.jpg to smartphone_442.jpg
Renamed image_547.jpg to smartphone_443.jpg
Renamed image_548.jpg to smartphone_444.jpg
Renamed image_549.jpg to smartphone_445.jpg
Renamed image_550.jpg to smartphone_446.jpg
Renamed image_551.jpg to smartphone_447.jpg
Renamed image_552.jpg to smartphone_448.jpg
Renamed image_553.jpg to smartphone_449.jpg
Renamed image_554.jpg to smartphone_450.jpg
Renamed image_555.jpg to smartphone_451.jpg
Renamed image_556.jpg to smartphone_452.jpg
Renamed image_557.jpg to smartphone_453.jpg
Renamed image_558.jpg to smartphone_454.jpg
Renamed image_562.jpg to smartphone_455.jpg
Renamed image_563.jpg to smartphone_456.jpg
Renamed image_564.jpg to smartphone_457.jpg
Renamed image_565.jpg to smartphone_458.jpg

## Data Transformation

In [23]:
# combine image file name with its path
image_path = "D:\\Machine_Learning\\Portfolio_Project_Machine_Learning\\Mobile_Phone_Recognition\\mobile_phone_images\\mobile_images"
images_ar = np.array([os.path.join(image_path, image_file) for image_file in image_files])

# Get all image filenames
image_files = os.listdir(img_dir)

# Sort the filenames numerically based on the number in the filename
image_files.sort(key=lambda x: int(x.split('_')[1].split('.')[0]))
images_ar = np.array(image_files)

# display shape of images and labels
print(image_files[:5])
print(f"Images: {images_ar.shape}")
print(f"Labels: {label_ar.shape}")

['smartphone_0.jpg', 'smartphone_1.jpg', 'smartphone_2.jpg', 'smartphone_3.jpg', 'smartphone_4.jpg']
Images: (802,)
Labels: (803,)

In [24]:
# implement function 4: construct a column list
def construct_columnframe(feature: str , samples: list) -> pd.DataFrame: 
  column_frame = pd.DataFrame()
  column_frame[feature] = samples
  return column_frame

# convert image urls and labels into dataframe
mobile_labels_df = construct_columnframe(feature="Mobile Phone Labels", samples=label_ar)
mobile_img_df = construct_columnframe(feature="Image File", samples=image_files)

In [26]:
mobile_img_df
# mobile_img_df.shape

             Image File
0      smartphone_0.jpg
1      smartphone_1.jpg
2      smartphone_2.jpg
3      smartphone_3.jpg
4      smartphone_4.jpg
..                  ...
797  smartphone_797.jpg
798  smartphone_798.jpg
799  smartphone_799.jpg
800  smartphone_800.jpg
801  smartphone_801.jpg

[802 rows x 1 columns]

In [27]:
mobile_img_df.loc[0]

Image File    smartphone_0.jpg
Name: 0, dtype: object

In [28]:
mobile_labels_df

                                   Mobile Phone Labels
0    Samsung SM-A556B Galaxy A55 5G Dual SIM 8GB 12...
1    Xiaomi 14 Ultra 5G 16GB/512GB White (White) Du...
2    Samsung Galaxy S22+ 5G 8GB/128GB Black (Phanto...
3    Samsung Galaxy A55 Smartphone 128GB 5G Midnigh...
4    Samsung Galaxy A03 Smartphone 64GB, 4GB RAM, D...
..                                                 ...
798  GenÃ©rico Galaxy S23 Ultra, 512GB Android Smar...
799                     Nokia 7230 Mobile Phone grey\n
800  Xiaomi Redmi 10 (2022) - Smartphone 64GB, 4GB ...
801  Xiaomi Redmi Note 10 5G 16.5 cm (6.5") Dual SI...
802  Samsung Galaxy S10 Dual SIM Prism White German...

[803 rows x 1 columns]

In [17]:
pd.concat([mobile_labels_df, mobile_img_df], axis=1)

                                   Mobile Phone Labels     Image File
0    Samsung SM-A556B Galaxy A55 5G Dual SIM 8GB 12...    image_4.jpg
1    Xiaomi 14 Ultra 5G 16GB/512GB White (White) Du...    image_5.jpg
2    Samsung Galaxy S22+ 5G 8GB/128GB Black (Phanto...    image_6.jpg
3    Samsung Galaxy A55 Smartphone 128GB 5G Midnigh...    image_7.jpg
4    Samsung Galaxy A03 Smartphone 64GB, 4GB RAM, D...    image_8.jpg
..                                                 ...            ...
798  GenÃ©rico Galaxy S23 Ultra, 512GB Android Smar...  image_950.jpg
799                     Nokia 7230 Mobile Phone grey\n  image_951.jpg
800  Xiaomi Redmi 10 (2022) - Smartphone 64GB, 4GB ...  image_952.jpg
801  Xiaomi Redmi Note 10 5G 16.5 cm (6.5") Dual SI...  image_953.jpg
802  Samsung Galaxy S10 Dual SIM Prism White German...            NaN

[803 rows x 2 columns]

In [30]:
mobile_labels_df["Mobile Phone Labels"].unique()

array(['Samsung SM-A556B Galaxy A55 5G Dual SIM 8GB 128GB Awesome Lemon EU\n',
       'Xiaomi 14 Ultra 5G 16GB/512GB White (White) Dual SIM\n',
       'Samsung Galaxy S22+ 5G 8GB/128GB Black (Phantom Black) Dual SIM SM-S906\n',
       'Samsung Galaxy A55 Smartphone 128GB 5G Midnight Blue\n',
       'Samsung Galaxy A03 Smartphone 64GB, 4GB RAM, Dual SIM, Blue\n',
       'Samsung Smartphone Galaxy S20, 5G, 12GB + 128GB, Grey\n',
       'SAMSUNG S20 ULTRA 128GB Phone - Cosmic gray\n',
       'Motorola Moto G54 256GB Blue 5G Android Smartphone 6.5 Inches 12GB RAM 16MP\n',
       'SAMSUNG - Smartphone Galaxy A14 5G Silver 6.6 IN 4GB 64GB Android 13\n',
       'Samsung Galaxy Note Pack 20 5G - 6.7" Display (AMOLED FHD+, 8GB RAM + 256GB Storage, Quad Rear Camera, 4300mAh Fast Charge 25W) Mystic Green [ES Version]\n',
       'Smartphone XIAOMI REDMIA3VERT\n',
       'XIAOMI Redmi 9A 32GB 4G Granite Grey\n',
       'Samsung Galaxy A55 5G 128GB EE Navy\n',
       'SAMSUNG - Galaxy A32 5G 4GB/128GB Black (Black Awesome) Dual SIM\n',
       'Samsung Galaxy Z Flip3 5G 8GB 128GB Phantom Black\n',
       'Samsung Galaxy S20 FE 5G 128GB/6GB G781 Dual SIM Verde\n',
       'Nokia XR20 5G 6GB/128GB Grey (Granite Gray) Dual SIM\n',
       'SAMSUNG Galaxy S20 FE 5G - Smartphone 128GB, 6GB RAM, Dual SIM, Cloud Mint\n',
       'Samsung Galaxy S20 FE 6GB/128GB Blue (Cloud Navy) Dual SIM G780\n',
       'Xiaomi 14 Ultra 5G 16/512GB MZB0G86EU\n',
       'Samsung A41 Dual SIM 64GB\n',
       'Samsung Galaxy A41 4GB/64GB Black (Prism Crush Black) Dual SIM A415\n',
       'SAMSUNG - Smartphone Galaxy A34 5G (256GB) Black\n',
       'Samsung SM-A356B Galaxy A35 5G Dual SIM 8GB RAM 256GB Awesome Iceblue EU\n',
       'SAMSUNG Galaxy S21 Ultra 5G 128GB, Black\n',
       'SAMSUNG - Galaxy A52S 5G 6GB/128GB Black (Black Awesome) Dual SIM SM-A528B\n',
       'Xiaomi Redmi Note 10 Pro 6GB/64GB Grey (Onyx Grey) Dual SIM M2101K6G\n',
       'Samsung Galaxy A52 5G Smartphone 128GB, 6GB RAM, Dual Sim, Black\n',
       'Motorola Moto E20 Smartphone 32 GB, 2 GB RAM, Dual SIM, Graphite Grey\n',
       'Xiaomi Redmi 10 (2022) - Smartphone 128GB, 4GB RAM, Dual Sim, Sea Blue\n',
       'Samsung Galaxy A52s 5G 128GB Awesome Mint Dual SIM\n',
       'Samsung Galaxy A52S 5G 6GB / 128GB Green (Awesome Mint) Dual SIM SM-A528B\n',
       'Motorola e30 2/32gb mineral grey\n',
       'Motorola e20 2/32gb coastal blue\n',
       'Samsung Galaxy S21+ 5G SM-G996B 17 cm (6.7") Dual SIM Android 11 USB Type-C 8 GB 128 GB 4800 mAh Black\n',
       'Xiaomi Redmi 10 (2022) - Smartphone 64GB, 4GB RAM, Dual Sim, Pebble White\n',
       'Samsung Galaxy S21 Plus 5G 8GB/256GB Black (Phantom Black) Dual SIM G996\n',
       'Nokia G11 Smartphone 6.5" [6.5] Dual SIM Android 11 4G USB Type-C 3GB 32GB 5050mAh Carbon Vegetal (G11 3/32GB D.SIM â€“ CHA\n',
       'SAMSUNG galaxy s21 128gb grey\n',
       'Xiaomi Xia Redmi Note 10 Pro 64-6-4G-bu | Xia Redmi Note 10 Pro 64GB/6GB Blue\n',
       'Samsung Galaxy S21 Plus 5G 8GB/256GB Purple (Phantom Purple) Dual SIM G996\n',
       'Smartphone Xiaomi Redmi Note 11 64GB Blue\n',
       'Samsung Galaxy S21 Plus 5G 8GB/128GB Black (Phantom Black) Dual SIM G996\n',
       'Xiaomi Mobile Phone Poco M5S 256GB ROM 8GB RAM Blue\n',
       'Nokia XR20, 6.67 Full HD+ Screen, Dual Camera 48MP with ZEISS Optics, Fast Charging 15W Wireless and 18W, RAM 4GB/64GB ROM, Can Be Used with Wet Hands and Gloves â€“ Black\n',
       'Samsung Galaxy Z Flip4, 5G Mobile Phone, SIM Card Not Included, Android, Folding Smartphone, 512 GB, Rose Gold, Free 12 Month Warranty Extension [Amazon Exclusive] â€“ FR Version\n',
       'Motorola Moto G50 Smartphone (6.5 Inch Max Vision HD+, Qualcomm Snapdragon 480 2.0GHz Octa-Core, 48MP Triple Camera, 5000mAh Battery, Dual SIM, 4/64GB, Android 11), Steel Grey\n',
       'Samsung Galaxy A52s 5G 6GB/128GB Black (Awesome Black) Dual SIM SM-A528B Enterprise Edition\n',
       'Xiaomi Redmi 12 Black 4GB + 128GB [Global Version]\n',
       'Nokia X30 5G Smartphone 128GB, 6GB RAM, 50MP Dual Camera, 6.43" AMOLED FHD+ Display, Android 12, 4200mAh Battery, Dual Sim, Blue, Version with Extra USB Type-C Cable\n',
       'Nokia G60 5G Smartphone 128 GB 16.7 cm (6.58") Black Android 12 Dual SIM\n',
       'Samsung - Mobile Phone Galaxy A33 5G 6GB/128GB Black (Awesome Black) Dual SIM A336\n',
       'XIAOMI REDMI NOTE 12 PRO 6128GB DS 4G GRAPHITE GRAY OEM\n',
       'Samsung Galaxy S23 S911B 5G Dual Sim EU 128GB Android Phantom Black\n',
       'SAMSUNG - Galaxy A53 5G 6GB/128GB Blue (Blue Awesome) Dual SIM A536B\n',
       'Motorola Edge 30 5G, Dual, 256GB 8GB Ram, Meteor Grey\n',
       'Samsung Galaxy S23 Ultra S918B 5G Dual Sim EU 256GB Android Phantom Black\n',
       'Samsung - Smartphone S21 FE 5G Dual SIM 128 GB\n',
       'Samsung Galaxy S22 Ultra 8Gb128Gb SMS908BDS White\n',
       'SAMSUNG Galaxy A53 128GB 5G Black\n',
       'Nokia C02 5.45 inch Android 12 (Go-Edition) Dual SIM Smartphone - 5.45 inch Rear Camera - Portrait Mode, 2GB RAM/32GB ROM, Rugged Construction with IP52 Rating, 3000mAh Battery - Cya\n',
       'SAMSUNG Galaxy A04S, Mobile Phone 4G 6.5", 32GB, SIM Card Not Included, Android, FR Version, Black\n',
       'Xiaomi Redmi 12C 6GB/128GB Grey (Graphite Grey) Dual SIM 22126RN91Y\n',
       'Xiaomi Redmi Note 11S 6Gb128Gb NFC Blue\n',
       'Xiaomi Redmi Note 10 pro 6gb128gb Bronze\n',
       'Xiaomi Poco X5 Pro 5G Dual Sim 8GB RAM 256GB - Black EU\n',
       'SAMSUNG - Galaxy A53 5G 6GB/128GB Black (Black Awesome) Dual SIM A536B\n',
       'Samsung Galaxy A33, 5G Mobile Phone 128GB Black, SIM Card Not Included, Android Smartphone, FR Version\n',
       'Nokia G22 6.52" HD+ Dual SIM Smartphone, Android 12, 50MP AI-Powered Camera, 3-Day Battery, 4GB/128GB Storage, 3 Year Monthly Security, 3-Year Warranty - Blue\n',
       'Xiaomi Redmi 10 4GB128GB NFC Gray\n',
       'Xiaomi Redmi A1 Dual SIM 2GB RAM 32GB Light Green EU\n',
       'Nokia G22, Dual, 128GB 4GB RAM, Meteor Grey\n',
       'Redmi Note 13 Black 8GB + 256GB\n',
       'Samsung Galaxy A55 Smartphone 256GB 5G Midnight Blue\n',
       'Xiaomi Redmi Note 13 Pro Smartphone, 5G, 8+256GB, 6.67 inch Display, 1.5K 120Hz AMOLED Display, Snapdragon 7s, 200MP Ultra Clear Camera with OIS, 5100mAh, 67W Turbo Charging, Blue\n',
       'Xiaomi Redmi Note 13 Pro 5G 8GB/256GB Purple (Aurora Purple) Dual SIM\n',
       'Xiaomi Redmi Note 13 Pro+ 5G 12GB/512GB Black (Midnight Black) Dual SIM\n',
       'Redmi Note 13 Blue 8GB + 256GB\n',
       'SAMSUNG Galaxy A35 SM-A356B Smartphone 6.6 Inch 8 GB RAM 256 GB Navy Blue\n',
       'Xiaomi Poco X6 Pro 5G Smartphone + Headphones, 8+256 Mobile Phone Without Contract, 64MP OIS Triple Camera, Bright Black (BE Version + 2 Year Warranty)\n',
       'XIAOMI - Redmi Note 13 Pro - 512GB - Midnight Black\n',
       'Xiaomi 13T Pro, AMOLED 144Hz, 12+512GB, Leica Camera, black\n',
       'Xiaomi Redmi Note 13 Pro 16.9 cm (6.67") Dual SIM Android 13 4G USB Type-C 8 GB 256 GB 5000 mAh Black\n',
       'Samsung SAMSUNG Galaxy A35 6.6 Inch Octa Core Smartphone 8GB RAM 256GB Blue\n',
       'Xiaomi Redmi 14C 4G 4GB/128GB Blue (Starry Blue) Dual SIM\n',
       'Xiaomi Redmi Note 13 Pro+ 5G Smartphone + Headphones, 2.8GHz 12GB+512GB Black (BE Version + 2 Year Warranty)\n',
       'Xiaomi Redmi Note 13 Smartphone + Headphones, 8GB+128GB Blue (BE Version + 2 Year Warranty)\n',
       'Redmi Note 13 256GB (Mint Green, Android 13, LTE)\n',
       'Motorola Moto G54 5G (6.5" FHD+ Screen, Dual Camera, 50MP, 8/256GB, 5000mAh, Android 13) Midnight Blue with Protective Case + Car Adapter\n',
       'Xiaomi Redmi Note 13 Pro 5G 512GB (Midnight Black, Android 13, 5G, 12 GB LPDDR4X)\n',
       'Xiaomi Poco X6 5G Smartphone + Headphones, 8+256 Cell Phone Without Contract, 64MP OIS Triple Camera, Grayish Blue (BE Version + 2 Year Warranty)\n',
       'Xiaomi Poco X6 Pro 5G 12GB/512GB Grey (Gray) Dual SIM\n',
       'Xiaomi Redmi Note 13 5G Smartphone + Headphones, 8GB+256GB Blue (BE Version + 2 Year Warranty)\n',
       'Xiaomi POCO M6 Pro, TÃ©lÃ©phone Mobile 8/256Go Violet, Carte SIM non Incluse, Smartphone Android, Version FR\n',
       'SAMSUNG galaxy a14 4g black 128gb\n',
       'Samsung Galaxy A35 5G, Dual, 256GB 8GB RAM, Navy Blue\n',
       'Samsung S901B/DS Galaxy S22 5G, Dual, 128GB 8GB RAM, Phantom Black\n',
       'Samsung SAMSUNG Galaxy A50 128GB Mobile Phone, Blue, Blue, Android 9.0 (Pie), Dual SIM\n',
       'Xiaomi POCO C65 8GB/256GB Purple (Purple) Dual SIM\n',
       'Samsung SM-A356B Galaxy A35 5G Dual SIM 8GB RAM 256GB Awesome Lilac EU\n',
       'Samsung Galaxy S10+ â€“ Unlocked 4G Smartphone (Screen: 6.4 Inches â€“ Dual SIM â€“ 128GB â€“ Android) â€“ Black\n',
       'Samsung Galaxy A12 Smartphone Black 64GB A125F Dual SIM Android 10.0\n',
       'SAMSUNG G991 Galaxy S21 5G 128GB Phantom Gray\n',
       'Nokia 7.2 Smartphone 64GB, 4GB RAM, Dual Sim, Charcoal Black\n',
       'SAMSUNG Galaxy Note 10 Plus Aura Glow Mobile Phone - 6.8 Inches/17.3 cm - CAM (12+16+12)/10MPX - OC - 256 GB - 12 GB RAM - 4G - Dual\n',
       'Samsung Galaxy Note 10 8GB/256GB Aura Glow Dual SIM N970\n',
       'Samsung Galaxy S21 5G 8GB/256GB Purple (Phantom Purple) Dual SIM G991\n',
       'Xiaomi Redmi Note 10 5G 16.5 cm (6.5") Dual SIM Android 11 USB Type-C 4 GB 128 GB 5000 mAh Grey\n',
       'Samsung Galaxy S10 Plus 8GB/128GB White Dual SIM G975\n',
       'Samsung Galaxy A40 5.9 Inch FHD+ sAmoled Infinity U Display Smartphone (4GB RAM, 64GB ROM, 16MP, Exynos 7904, Fast Charging), Black\n',
       'Samsung Galaxy S8 Black (Midnight Black) Single SIM G950\n',
       'Nokia 105 (2017) Black (Black) Dual SIM\n',
       'Samsung Keystone 2 GT-E1205Y Black SIM Free\n',
       'Xiaomi Redmi 12 Smartphone, MediaTek G88 Processor, 50MP Main Camera, 90Hz FHD+ Display, 5000mAh Battery (8+256GB Black)\n',
       'Samsung Galaxy A70 â€“ 4G Smartphone (6.7 Inches â€“ 128GB â€“ 6 GB RAM) â€“ Blue â€“ Other Version\n',
       'Samsung Galaxy Note 10 8GB/256GB Black Dual SIM N970\n',
       'Samsung Galaxy S22 5G 128GB Bora Purple EU [15.39cm (6.1") OLED Display, Android 12, 50MP Triple-Kamera]\n',
       'Samsung Galaxy S10 8GB / 128GB Dual SIM G973 Unprinted\n',
       'SAMSUNG - Galaxy S21 Plus 5G 8GB/128GB Purple (Phantom Purple) Dual SIM G996\n',
       'Samsung Galaxy A53 5G 256GB Black\n',
       'Apple iPhone 12 Mini, 64GB, Green Green One\n',
       'Apple iPhone 13 128GB 6.1" Midnight ITA MLPF3QL/A\n',
       'Apple iPhone 13 128GB 6.1" Starlight ITA MLPG3QL/A\n',
       'Apple iPhone 12 Pro Cell Phone 128GB MGMM3QL/A Gold Italy\n',
       'Apple iPhone 12 Pro Max (128GB) - Graphite\n',
       'Apple iPhone 12 Mini - 64 GB - White\n',
       'Apple iPhone 12 64GB Blue EU\n',
       'Apple iPhone 14 (128 Go) - Jaune\n',
       'Apple iPhone 14 Plus (512 Go) - Jaune\n',
       'Samsung Milwaukee A047F Galaxy A04s Unlocked 32GB/3GB RAM Dual SIM Green\n',
       'Samsung Galaxy S21 5G SM-G991B 15.8 cm (6.2") Dual SIM Android 11 USB Type-C 8 GB 128 GB 4000 mAh Purple\n',
       'Samsung Galaxy A72 6GB/128GB Blue (Blue Impressive) Dual SIM\n',
       'Xiaomi Redmi 10 Smartphone, 4GB RAM + 64GB ROM, 6.5" FHD + DotDisplay, MediaTek Helio G88 Octa-Core, Quad 50MP AI Camera and 8MP Front Camera (4GB+64GB, Grey)\n',
       'Motorola Moto G54 256GB Light Blue 5G Android Smartphone 6.5 Inches 8GB RAM 12MP\n',
       'Samsung A136B, All Carriers, 4GB, Galaxy A13 5G 64GB/4GB RAM, Dual SIM, White\n',
       'Samsung Galaxy A52 6GB/128GB Blue (Awesome Blue) Dual SIM A525F\n',
       'Samsung Galaxy S21 G991 5G Dual SIM 6GB RAM 128GB - Grey EU\n',
       'Samsung Galaxy S21 5G SM-G991B 15.8 cm (6.2") Dual SIM Android 11 USB Type-C 8 GB 256 GB 4000 mAh Purple\n',
       'Samsung Galaxy A12 4GB/128GB White Dual SIM A125F\n',
       'Samsung Galaxy S21 5G 8GB/128GB White (Phantom White) Dual SIM G991\n',
       'NOKIA Mobile Phone 150 (2020) Dual SIM, 2.4" Screen, Camera, FM Radio, MP3 Player, Expandable MicroSD up to 32GB, Red\n',
       'Samsung Galaxy A21s 3GB/32GB White Dual SIM A217\n',
       'Samsung Galaxy S20 Cosmic Gray G980F Dual SIM 128GB Android 10.0 Smartphone\n',
       'Xiaomi M9LITE 6+128GB White EU\n',
       'Samsung Smartphone Galaxy S9+ (6.2 inches) 64 GB internal memory, dual sim) â€“ German version\n',
       'Xiaomi Poco C40 Unlocked 3+32GB DS 4G Power Black OEM\n',
       'SAMSUNG Free phone S20 FE 4G G780 6/128 Lavan\n',
       'Apple iPhone 12 6.1 inch 64GB Green Europe\n',
       'Samsung Galaxy Mega GT-i9205 6.3 inch Cortex A15 Dual Core 1.7 GHz 1.5 GB RAM 8 MP Camera Android 4.2 Black\n',
       'Samsung Galaxy Core Prime SM-G360F 8GB 4G Unlocked Movistar Smartphone (Android, SIM Only, MicroSIM, GSM, UMTS, WCDMA, LTE) â€“ Silver\n',
       'Samsung E1272 1.7 Inch 83g Red Mobile Phones (Dual SIM, Alarm Clock, Calculator, Calendar, Notes, 2G, Micro-USB A, MP3, 160 x 128 pixels)\n',
       'Samsung G900 Galaxy S5 Smartphone 16GB Black [Italy]\n',
       'Samsung Galaxy S5 Unlocked Smartphone 4G (Screen: 5.1 Inches â€“ 16 GB â€“ Android 4.4.2 KitKat) Black\n',
       'Samsung Galaxy S5 Smartphone (5.1 Inch) Touch Screen, Quad-Core 2.5GHz Processor, 2GB RAM, 16MP Camera, Android 4.4 OS) - White [T-Mobile Marking]\n',
       'Samsung Galaxy A3 A300FU LTE 16GB White Unlocked\n',
       'Samsung Galaxy Note Edge Smartphone with 5.6 Inch Touch Screen, 32 GB Memory, Android 4.4, Charcoal Black\n',
       'Samsung Galaxy Alpha 4.7" Super AMOLED Octa-Core Processor 12MP Android Camera Gold\n',
       'POCO C40 3+32GB DS 4G POCO YELLOW OEM\n',
       'Samsung Galaxy Xcover 3 4.5 Inch Mobile Phone with Touch Screen 8GB Memory, Android 4.4, Dark Silver\n',
       'Samsung Galaxy Note Edge Smartphone with 5.6 Inch Super AMOLED Display, 2.7 GHz Quad-Core Processor, 32 GB Internal Memory, 16 MP Camera, Android 4.4 Frosted White\n',
       'Galaxy S5 Mini Samsung Galaxy S5 Mini Smartphone (4.5 Inch) Touch Screen, 8 Megapixel Camera, 1.4 GHz Quad-Core Processor, Android 4.4 Black [EU Version]\n',
       'Motorola Moto G (2nd Gen XT1068) 8GB White\n',
       'SAMSUNG S5 4G 16GB\n',
       'Samsung Galaxy S5 Smartphone (5.1 Inch Touch Screen) 2.5GHz Quad Core Processor, 2GB RAM, 16MP Camera, Android 4.4 OS) - Black [EU Version]\n',
       'Samsung Galaxy S5 Unlocked Smartphone 4G (Screen: 5.1 Inches â€“ 16 GB â€“ Android 4.4.2 KitKat) White\n',
       'Samsung Galaxy S5 Smartphone with 5.1 Inch Touch Screen, 2.5GHz Quad-Core Processor, 2GB RAM, 16MP Camera, Android 4.4 OS Black [T-Mobile Brand]\n',
       'Samsung Galaxy S22 Ultra, 5G Mobile Phone 128GB Black, SIM Card Not Included, Android Smartphone, FR Version\n',
       'Samsung Galaxy S6 Edge Unlocked Smartphone 4G (32 GB - 5.1 Inch Screen, Single SIM - Android 5.0 Lollipop) Black\n',
       'Samsung Galaxy S6 Edge Smartphone (5.1 Inches), Touch Screen, 32GB Memory, Android 5.0, Black [T-Mobile Brand]\n',
       'Samsung Galaxy S6 Edge Unlocked Android Smartphone (5.1 Inch Screen, 16MP Camera, 128GB, Quad-Core 2.1GHz, 3GB RAM, White [Spanish Model]\n',
       'Sam Galaxy A13 EU-DS-64-4-5G-WH SAMSUNG Galaxy A13 5G EU 64/4GB White\n',
       'Xiaomi Xia Poco X4 GT 128-8-5G sr X4 GT 128G Silver\n',
       'Samsung S6 Edge Tim G925F\n',
       'Samsung Galaxy S6 Edge Unlocked Android Smartphone (5.1 Inch Screen, 16MP Camera, 32GB, Quad-Core 2.1GHz, 3GB RAM, Black (Imported from Italy)\n',
       'Samsung Galaxy S6 Edge Unlocked Smartphone 4G (Screen: 5.1 Inches - 32GB - Nano SIM Card - Android Lollipop 5) White (Imported from Europe)\n',
       'SAMSUNG S6 Edge 32 GB\n',
       'Samsung Galaxy S6 Edge Smartphone (5.1 Inch Touch Screen), 32GB Memory, Android 5.0 White [T-Mobile Brand]\n',
       'Samsung Galaxy S6 Smartphone (5.1 Inches), Touch Screen, 32GB Memory, Android 5.0 White [T-Mobile Brand]\n',
       'Samsung Galaxy S6 Edge Unlocked Android Smartphone 5.1" Screen 16MP 32GB Quad-Core 2.1GHz 3GB RAM Gold\n',
       'Motorola Moto G62 5G 6.5" FHD+ 6/128GB Grey\n',
       'Samsung SM-M536 Galaxy M55 Dual SIM 5G 8GB RAM 128GB Green EU\n',
       'Samsung Galaxy S7 Edge Smartphone (5.5 inches, 32 GB internal memory)\n',
       'Samsung Galaxy S7 Edge Unlocked Smartphone 5.5 Inches (Android 6.0, Dual Edge Super AMOLED Display, 12MP Rear Camera and Front 5.5 MP, 32 GB) [Spanish Version: Includes Pay] Gold\n',
       'Samsung G935 Galaxy S7 Smartphone, LTE, 5.1" SAMOLED Display, 32GB Internal Memory, 4GB RAM, Black, Tim [Italy]\n',
       'Galaxy S7 Edge Smartphone Pink\n',
       'Sam Galaxy A52s EE-128-6-5G-bk | Samsung Galaxy A52s DS EE 128/6 Black\n',
       'Samsung Galaxy A5 2017 Unlocked 4G Smartphone (Screen: 5.2 Inches â€“ 32 GB â€“ Nano-SIM â€“ Android 6.0) Blue (European SIM Card Only)\n',
       'Samsung SM-A520F Galaxy A5 (2017) 32GB Black Sky EU\n',
       'Samsung Galaxy XCover 3 VE Unlocked Smartphone 4G (Screen: 4.5 Inches â€“ 8 GB â€“ Single Micro-SIM â€“ Android) Dark Silver\n',
       'Samsung Galaxy S7 Edge Unlocked Smartphone 4G 5.5 Inch 32GB 4GB RAM Android Black\n',
       'Samsung SM-A556B Galaxy A55 5G Dual SIM 8GB 128GB Awesome Navy EU\n',
       'Galaxy A55 5G 256GB, Handy Awesome Lemon, Android 14.8 GB\n',
       'Samsung Galaxy S24 Smartphone 128GB Indigo\n',
       'Samsung Galaxy A15 4G Yellow 128GB\n',
       'Samsung A15 SM-A156B 4+128GB DS 5G Blue OEM\n',
       'Samsung Galaxy Xcover 4 Smartphone (5 inch touch screen) 16 GB memory, Android 7.0 Nougat) Black\n',
       'Xiaomi Redmi Note 12 5G 128GB/4GB Dual-SIM onyx-grey\n',
       'Nokia X3 (Ovi, Ultra-Short Wave Radio, 3.2 MP) Mobile Phone Without Contract, Branding, Unlocked Red/Black\n',
       'ATI Xiaomi Redmi Note 12 Pro 5G Smartphone, 8GB RAM, 128GB ROM, Midnight Black\n',
       'Xiaomi Smartphone Redmi Note 13 6.67" 8 GB RAM 256 GB Black\n',
       'Xiaomi POCO C65 6GB/128GB Purple (Purple) Dual SIM\n',
       'Xiaomi Smartphone Redmi Note 13 6.67" 6 GB RAM 128 GB Blue\n',
       'SAMSUNG Galaxy S23 Smartphone Green 6.1" 256GB Octa Core 8GB RAM\n',
       'Nokia C21 Plus 32GB/2GB RAM, Dual SIM, Dark Cyan\n',
       'Samsung Galaxy J5 (2017) SM-J530F 5.2" 2GB 16GB 4G Black 3000mAh (Refurbished)\n',
       'Samsung Galaxy S8 LTE 64GB SM-G950F Blue SIM Free\n',
       'Samsung Galaxy S8+ Mobile Phone Blue\n',
       'Samsung Galaxy S8 Smartphone, 64 GB, Orchid Grey, German Version (Refurbished)\n',
       'Samsung Galaxy S8+ VODAFONE\n',
       'Samsung 356430 Smartphone Galaxy S8 (5.8 Inch Screen) 64 GB, Android 7.0 Nougat) Black\n',
       'Samsung Galaxy S8 G950F 64G Midnight Black\n',
       'Samsung SM-G950F Galaxy S8 64GB Midnight Black EU\n',
       'Moto G 5Âª GeneraciÃ³n Plus - Android 7 Free Smartphone (5.2 Inch Trousers, Full HD, 4G, 12MP Dual Pixel, 3GB RAM, 32GB, Qualcomm Snapdragon 2.0GHz), Color Dorado\n',
       'Samsung Z Flip6 256GB Yellow EU\n',
       'Nokia G22 TA-1528 DS 4/64 EURO1 Blue\n',
       'Samsung Galaxy A15 5G Smartphone 128GB Lime\n',
       'SAMSUNG Compatible with Galaxy S22 5G Green 128GB\n',
       'Samsung Galaxy S21 FE 5G, Android Smartphone, 6.4 Zoll Dynamic AMOLED Display, 4.500 mAh Akku, 128 GB/6 GB RAM, Handy in Graphite, inkl. 36 Monate Manufacturer Warranty [Exclusive to Amazon]\n',
       'Samsung Galaxy A8 Vodafone 0706901 Samsung SM.ph.Samsung gal A8 Black\n',
       'Galaxy A8 (2018) Dual SIM 32GB SM-A530F/DS Gold\n',
       'Motorola Moto X4 32GB Black Dual SIM\n',
       'Samsung Galaxy Note 8 Midnight Black Sm-n950 F Italy\n',
       'SAMSUNG Galaxy S9 64GB (Single SIM) - Carbon Black - Android 8.0 - International Version (Refurbished)\n',
       'Samsung Galaxy S9 (5.8", Wi-Fi, Bluetooth 64 GB, 4 GB RAM, Dual SIM, 12 MP, Android 8.0 Oreo), Blue - Other European Version\n',
       'Samsung SM-G960XZKAITV Smartphone SAMSUNG Galaxy S9 (6.2 Inches, Wi-Fi, Bluetooth 64 GB, 6 GB RAM, 12 MP, Android 8.0 Oreo) Black Italian Version\n',
       'Samsung Galaxy S9 Smartphone (5.8 inch Touch Screen, 64GB Internal Memory, Android, Dual SIM) Italian Version, Midnight Black\n',

## Data Cleaning

Preprocessing the mobile label data based on these tasks/ 

+ remove special characters 
+ extract only brand labels

In [30]:
# retrieve mobile label data
image_df["Mobile_label"] = image_df["Mobile_label"].apply(lambda text: text.lower())
image_df["Mobile_brand"] = image_df["Mobile_label"].str.split(" ", expand=True)[0]

In [31]:
# write a unique list of labels
image_df["Mobile_brand"].unique()

array(['xiaomi', 'samsung', 'nokia', 'motorola', 'smartphone', 'poco',
       'redmi', 'oneplus', 'apple', 'galaxy', 'sam', 'ati', 'moto',
       'telecom', 'xia', 'iphone', 'unlocked', 'free', 'm4'], dtype=object)

In [33]:
# replace abbreviation by useful labels
image_df[image_df["Mobile_brand"] == "xia"]["Mobile_label"]

242    xia ds 13 5g 8+256 glo wht\n
Name: Mobile_label, dtype: object

In [28]:
image_df["Mobile_label"].tolist()

['xiaomi 14 ultra 5g 16gb/512gb white (white) dual sim\n',
 'samsung galaxy a55 smartphone 128gb 5g midnight blue\n',
 'samsung - smartphone galaxy a14 5g silver 6.6 in 4gb 64gb android 13\n',
 'samsung smartphone galaxy s20, 5g, 12gb + 128gb, grey\n',
 'samsung galaxy note pack 20 5g - 6.7" display (amoled fhd+, 8gb ram + 256gb storage, quad rear camera, 4300mah fast charge 25w) mystic green [es version]\n',
 'xiaomi redmi 9a 32gb 4g granite grey\n',
 'samsung - galaxy a32 5g 4gb/128gb black (black awesome) dual sim\n',
 'samsung galaxy z flip3 5g 8gb 128gb phantom black\n',
 'samsung galaxy s20 fe 5g 128gb/6gb g781 dual sim verde\n',
 'samsung galaxy s22+ 5g 8gb/128gb black (phantom black) dual sim sm-s906\n',
 'nokia xr20 5g 6gb/128gb grey (granite gray) dual sim\n',
 'samsung galaxy s20 fe 5g - smartphone 128gb, 6gb ram, dual sim, cloud mint\n',
 'xiaomi 14 ultra 5g 16/512gb mzb0g86eu\n',
 'samsung galaxy s20 fe 6gb/128gb blue (cloud navy) dual sim g780\n',
 'samsung a41 dual sim 64gb\n',
 'samsung galaxy a41 4gb/64gb black (prism crush black) dual sim a415\n',
 'samsung - smartphone galaxy a34 5g (256gb) black\n',
 'samsung sm-a356b galaxy a35 5g dual sim 8gb ram 256gb awesome iceblue eu\n',
 'samsung galaxy s24 ultra 12/1tb purple\n',
 'samsung galaxy s24 ultra 12/1tb black\n',
 'motorola moto g54 256gb blue 5g android smartphone 6.5 inches 12gb ram 16mp\n',
 'xiaomi 13t pro smartphone 12gb/512gb/6.67ft/5g/ prado green\n',
 'samsung a135f/dsn galaxy a13 dual sim (6.6 inches - 4/128gb) black\n',
 'samsung galaxy note20 ultra 5g brown\n',
 'samsung - galaxy a52s 5g 6gb/128gb black (black awesome) dual sim sm-a528b\n',
 'samsung galaxy a52 5g smartphone 128gb, 6gb ram, dual sim, black\n',
 'motorola moto e20 smartphone 32 gb, 2 gb ram, dual sim, graphite grey\n',
 'xiaomi redmi 10 (2022) - smartphone 128gb, 4gb ram, dual sim, sea blue\n',
 'samsung galaxy a52s 5g 128gb awesome mint dual sim\n',
 'motorola e30 2/32gb mineral grey\n',
 'xiaomi redmi note 11s 4g nfc 128gb/6gb dual sim grey\n',
 'motorola e20 2/32gb coastal blue\n',
 'samsung galaxy s21+ 5g sm-g996b 17 cm (6.7") dual sim android 11 usb type-c 8 gb 128 gb 4800 mah black\n',
 'xiaomi redmi note 10 pro 6gb/64gb grey (onyx grey) dual sim m2101k6g\n',
 'xiaomi redmi 10 (2022) - smartphone 64gb, 4gb ram, dual sim, pebble white\n',
 'samsung galaxy s21 128gb grey\n',
 'xiaomi xia redmi note 10 pro 64-6-4g-bu | xia redmi note 10 pro 64gb/6gb blue\n',
 'samsung galaxy s21 plus 5g 8gb/256gb purple (phantom purple) dual sim g996\n',
 'smartphone xiaomi redmi note 11 64gb blue\n',
 'samsung galaxy s21 plus 5g 8gb/128gb black (phantom black) dual sim g996\n',
 'xiaomi mobile phone poco m5s 256gb rom 8gb ram blue\n',
 'nokia xr20, 6.67 full hd+ screen, dual camera 48mp with zeiss optics, fast charging 15w wireless and 18w, ram 4gb/64gb rom, can be used with wet hands and gloves â€“ black\n',
 'samsung galaxy z flip4, 5g mobile phone, sim card not included, android, folding smartphone, 512 gb, rose gold, free 12 month warranty extension [amazon exclusive] â€“ fr version\n',
 'motorola moto g50 smartphone (6.5 inch max vision hd+, qualcomm snapdragon 480 2.0ghz octa-core, 48mp triple camera, 5000mah battery, dual sim, 4/64gb, android 11), steel grey\n',
 'motorola edge 20 smartphones, 108mp, 5g, 6.7 inch display 144hz hdr10+ oled fullhd+, qualcomm snapdragon 778g, 30x super zoom, 4000mah, dual sim, 6/128gb, android 11, grey (frosted grey)\n',
 'samsung galaxy s21 ultra 5g dual sim smartphone 256gb 6.8" dual sim androidâ„¢ 11 black\n',
 'xiaomi redmi note 11 pro+ 5g 8+256 graphite gray\n',
 'xiaomi redmi note 11 pro 5g 6gb/64gb white (polar white) dual sim\n',
 'xiaomi redmi 12 black 4gb + 128gb [global version]\n',
 'nokia g60 5g smartphone 128 gb 16.7 cm (6.58") black android 12 dual sim\n',
 'motorola edge 30 5g, dual, 256gb 8gb ram, meteor grey\n',
 'samsung galaxy s23 s911b 5g dual sim eu 128gb android phantom black\n',
 'samsung galaxy s23 ultra s918b 5g dual sim eu 256gb android phantom black\n',
 'samsung galaxy s22 ultra 8gb128gb sms908bds white\n',
 'samsung - smartphone s21 fe 5g dual sim 128 gb\n',
 'samsung galaxy a53 128gb 5g black\n',
 'samsung galaxy a04s, mobile phone 4g 6.5", 32gb, sim card not included, android, fr version, black\n',
 'xiaomi redmi 12c 6gb/128gb grey (graphite grey) dual sim 22126rn91y\n',
 'xiaomi redmi note 11s 6gb128gb nfc blue\n',
 'xiaomi redmi note 10 pro 6gb128gb bronze\n',
 'xiaomi poco x5 pro 5g dual sim 8gb ram 256gb - black eu\n',
 'samsung galaxy a33, 5g mobile phone 128gb black, sim card not included, android smartphone, fr version\n',
 'nokia g22 6.52" hd+ dual sim smartphone, android 12, 50mp ai-powered camera, 3-day battery, 4gb/128gb storage, 3 year monthly security, 3-year warranty - blue\n',
 'xiaomi redmi 10 4gb128gb nfc gray\n',
 'xiaomi redmi a1 dual sim 2gb ram 32gb light green eu\n',
 'nokia g22, dual, 128gb 4gb ram, meteor grey\n',
 'xiaomi smartphone redmi 12 8gb 256gb polar silver octacore/6.79 ?fhd+/8 mp/50+8+2 mp/18 w\n',
 'poco x5 pro 5g 256gb (blue, dual sim, android 12)\n',
 'samsung galaxy a23 5g, android 12 smartphone, 6.6 inch infinity-v display, 4 gb ram and 128 gb internal memory, 5000 mahâ³ battery, black (italian version)\n',
 'samsung galaxy s23 5g sms911bds 8gb256gb lavender\n',
 'samsung galaxy s21 fe 5g android smartphone 128gb sim free display 6.4 inch dynamic amoled 2x, 3 rear cameras, graphite [italian version]\n',
 'samsung a135 galaxy a13 android smartphone, display infinity-v 6.6 inches, android 12, 4gb ram and 128gb internal memory expandable 5000mahâ³ battery, blue light [italian version]\n',
 'redmi note 13 black 8gb + 256gb\n',
 'samsung galaxy a55 smartphone 256gb 5g midnight blue\n',
 'xiaomi redmi note 13 pro 5g 8gb/256gb purple (aurora purple) dual sim\n',
 'samsung galaxy a35 sm-a356b smartphone 6.6 inch 8 gb ram 256 gb navy blue\n',
 'redmi note 13 blue 8gb + 256gb\n',
 'xiaomi redmi note 13 pro smartphone, 5g, 8+256gb, 6.67 inch display, 1.5k 120hz amoled display, snapdragon 7s, 200mp ultra clear camera with ois, 5100mah, 67w turbo charging, blue\n',
 'xiaomi redmi note 13 pro 16.9 cm (6.67") dual sim android 13 4g usb type-c 8 gb 256 gb 5000 mah black\n',
 'xiaomi redmi 14c 4g 4gb/128gb black (midnight black) dual sim\n',
 'xiaomi redmi note 13 pro+ 5g 12gb/512gb black (midnight black) dual sim\n',
 'xiaomi poco x6 pro 5g smartphone + headphones, 12+512 mobile phone without contract, 64mp ois triple camera, bright black (be version + 2 year warranty)\n',
 'xiaomi poco x6 pro 5g 12gb/512gb grey (gray) dual sim\n',
 'xiaomi poco x6 5g smartphone + headphones, 8+256 cell phone without contract, 64mp ois triple camera, grayish blue (be version + 2 year warranty)\n',
 'samsung galaxy a14 4g black 128gb\n',
 'xiaomi redmi note 13 pro 5g 512gb (midnight black, android 13, 5g, 12 gb lpddr4x)\n',
 'xiaomi poco m6 pro 12gb/512gb purple (purple) dual sim\n',
 'redmi note 13 256gb (mint green, android 13, lte)\n',
 'xiaomi - redmi note 13 pro - 512gb - midnight black\n',
 'xiaomi redmi 14c 4g 4gb/128gb green (sage green) dual sim\n',
 'xiaomi redmi note 13 5g smartphone + headphones, 8gb+256gb tarnish (be version + 2 year warranty)\n',
 'xiaomi redmi note 13 4g unlocked smartohone, 8gb+256gb, 6.67" 120hz amoled display, 108mp triple camera, snapdragon 685 processor, 5000mah battery, 33w fast charge (midnight black)\n',
 'xiaomi redmi 13c 6gb ram 128gb rom [global version] (midnight black)\n',
 'xiaomi redmi 13c 8gb/256gb white (glacier white) dual sim\n',
 'samsung galaxy z fold5 512gb black\n',
 'xiaomi redmi 13c 17.1 cm (6.74") dual sim 4g usb type-c 8 gb 256 gb 5000 mah blue,navy\n',
 'oneplus 8 pro 17.2 cm (6.78") 8 gb 128 gb dual sim 5g usb type-c black oxygen os 4510 mah 8 pro, 17.2 cm (6.78"), 8 gb, 128 gb, 48 mp, oxygen os, black\n',
 'samsung galaxy a35 5g, dual, 256gb 8gb ram, navy blue\n',
 'xiaomi poco c65 8gb/256gb purple (purple) dual sim\n',
 'samsung galaxy a12 smartphone black 64gb a125f dual sim android 10.0\n',
 'samsung s901b/ds galaxy s22 5g, dual, 128gb 8gb ram, phantom black\n',
 'samsung g991 galaxy s21 5g 128gb phantom gray\n',
 'nokia 7.2 smartphone 64gb, 4gb ram, dual sim, charcoal black\n',
 'samsung galaxy s21 5g 8gb/256gb purple (phantom purple) dual sim g991\n',
 'xiaomi redmi note 10 5g 16.5 cm (6.5") dual sim android 11 usb type-c 4 gb 128 gb 5000 mah grey\n',
 'samsung sm-a356b galaxy a35 5g dual sim 8gb ram 256gb awesome lilac eu\n',
 'samsung galaxy s10+ â€“ unlocked 4g smartphone (screen: 6.4 inches â€“ dual sim â€“ 128gb â€“ android) â€“ black\n',
 'samsung galaxy s10 plus 8gb/128gb white dual sim g975\n',
 'samsung galaxy a40 5.9 inch fhd+ samoled infinity u display smartphone (4gb ram, 64gb rom, 16mp, exynos 7904, fast charging), black\n',
 'samsung galaxy s8 black (midnight black) single sim g950\n',
 'oneplus 9 6.5" (6.55) dual sim oxygen os 5g usb type-c 4500mah, 8gb 128gb,blue\n',
 'nokia 105 (2017) black (black) dual sim\n',
 'samsung keystone 2 gt-e1205y black sim free\n',
 'xiaomi redmi 12 smartphone, mediatek g88 processor, 50mp main camera, 90hz fhd+ display, 5000mah battery (8+256gb black)\n',
 'samsung galaxy a70 â€“ 4g smartphone (6.7 inches â€“ 128gb â€“ 6 gb ram) â€“ blue â€“ other version\n',
 'samsung galaxy note 10 8gb/256gb black dual sim n970\n',
 'samsung galaxy s22 5g 128gb bora purple eu [15.39cm (6.1") oled display, android 12, 50mp triple-kamera]\n',
 'samsung galaxy s10 8gb / 128gb dual sim g973 unprinted\n',
 'xiaomi redmi 10c 3 gb ram 64 gb mint green\n',
 'samsung - galaxy s21 plus 5g 8gb/128gb purple (phantom purple) dual sim g996\n',
 'samsung galaxy a53 5g 256gb black\n',
 'apple iphone 12 mini, 64gb, green green one\n',
 'apple iphone 13 128gb 6.1" midnight ita mlpf3ql/a\n',
 'apple iphone 13 128gb 6.1" starlight ita mlpg3ql/a\n',
 'apple iphone 12 pro cell phone 128gb mgmm3ql/a gold italy\n',
 'apple iphone 12 pro max (128gb) - graphite\n',
 'apple iphone 12 mini - 64 gb - white\n',
 'apple iphone 12 64gb blue eu\n',
 'apple iphone 14 (128 go) - jaune\n',
 'apple iphone 14 plus (512 go) - jaune\n',
 'samsung galaxy s21 plus 5g 8gb/128gb black (phantom black) dual sim g996\n',
 'samsung milwaukee a047f galaxy a04s unlocked 32gb/3gb ram dual sim green\n',
 'samsung galaxy s21 5g sm-g991b 15.8 cm (6.2") dual sim android 11 usb type-c 8 gb 128 gb 4000 mah purple\n',
 'xiaomi redmi 10 smartphone, 4gb ram + 64gb rom, 6.5" fhd + dotdisplay, mediatek helio g88 octa-core, quad 50mp ai camera and 8mp front camera (4gb+64gb, grey)\n',
 'motorola moto g54 256gb light blue 5g android smartphone 6.5 inches 8gb ram 12mp\n',
 'samsung a136b, all carriers, 4gb, galaxy a13 5g 64gb/4gb ram, dual sim, white\n',
 'samsung galaxy s21 g991 5g dual sim 6gb ram 128gb - grey eu\n',
 'samsung galaxy s21 5g sm-g991b 15.8 cm (6.2") dual sim android 11 usb type-c 8 gb 256 gb 4000 mah purple\n',
 'samsung galaxy a12 4gb/128gb white dual sim a125f\n',
 'samsung galaxy s21 5g 8gb/128gb white (phantom white) dual sim g991\n',
 'nokia mobile phone 150 (2020) dual sim, 2.4" screen, camera, fm radio, mp3 player, expandable microsd up to 32gb, red\n',
 'samsung galaxy a21s 3gb/32gb white dual sim a217\n',
 'samsung galaxy s20 cosmic gray g980f dual sim 128gb android 10.0 smartphone\n',
 'xiaomi m9lite 6+128gb white eu\n',
 'samsung galaxy a52 6gb/128gb blue (awesome blue) dual sim a525f\n',
 'samsung smartphone galaxy s9+ (6.2 inches) 64 gb internal memory, dual sim) â€“ german version\n',
 'xiaomi poco c40 unlocked 3+32gb ds 4g power black oem\n',
 'samsung free phone s20 fe 4g g780 6/128 lavan\n',
 'apple iphone 12 6.1 inch 64gb green europe\n',
 'samsung galaxy mega gt-i9205 6.3 inch cortex a15 dual core 1.7 ghz 1.5 gb ram 8 mp camera android 4.2 black\n',
 'samsung galaxy core prime sm-g360f 8gb 4g unlocked movistar smartphone (android, sim only, microsim, gsm, umts, wcdma, lte) â€“ silver\n',
 'samsung g900 galaxy s5 smartphone 16gb black [italy]\n',
 'samsung galaxy s5 unlocked smartphone 4g (screen: 5.1 inches â€“ 16 gb â€“ android 4.4.2 kitkat) black\n',
 'samsung galaxy s5 smartphone (5.1 inch) touch screen, quad-core 2.5ghz processor, 2gb ram, 16mp camera, android 4.4 os) - white [t-mobile marking]\n',
 'samsung galaxy a3 a300fu lte 16gb white unlocked\n',
 'samsung galaxy note edge smartphone with 5.6 inch touch screen, 32 gb memory, android 4.4, charcoal black\n',
 'samsung galaxy alpha 4.7" super amoled octa-core processor 12mp android camera gold\n',
 'poco c40 3+32gb ds 4g poco yellow oem\n',
 'samsung galaxy xcover 3 4.5 inch mobile phone with touch screen 8gb memory, android 4.4, dark silver\n',
 'samsung galaxy note edge smartphone with 5.6 inch super amoled display, 2.7 ghz quad-core processor, 32 gb internal memory, 16 mp camera, android 4.4 frosted white\n',
 'galaxy s5 mini samsung galaxy s5 mini smartphone (4.5 inch) touch screen, 8 megapixel camera, 1.4 ghz quad-core processor, android 4.4 black [eu version]\n',
 'motorola moto g (2nd gen xt1068) 8gb white\n',
 'samsung s5 4g 16gb\n',
 'samsung galaxy s5 smartphone (5.1 inch touch screen) 2.5ghz quad core processor, 2gb ram, 16mp camera, android 4.4 os) - black [eu version]\n',
 'samsung galaxy s5 unlocked smartphone 4g (screen: 5.1 inches â€“ 16 gb â€“ android 4.4.2 kitkat) white\n',
 'samsung galaxy s5 smartphone with 5.1 inch touch screen, 2.5ghz quad-core processor, 2gb ram, 16mp camera, android 4.4 os black [t-mobile brand]\n',
 'samsung galaxy s22 ultra, 5g mobile phone 128gb black, sim card not included, android smartphone, fr version\n',
 'samsung galaxy s6 edge unlocked smartphone 4g (32 gb - 5.1 inch screen, single sim - android 5.0 lollipop) black\n',
 'samsung galaxy s6 edge smartphone (5.1 inches), touch screen, 32gb memory, android 5.0, black [t-mobile brand]\n',
 'samsung galaxy s6 edge unlocked android smartphone (5.1 inch screen, 16mp camera, 128gb, quad-core 2.1ghz, 3gb ram, white [spanish model]\n',
 'sam galaxy a13 eu-ds-64-4-5g-wh samsung galaxy a13 5g eu 64/4gb white\n',
 'xiaomi xia poco x4 gt 128-8-5g sr x4 gt 128g silver\n',
 'samsung s6 edge tim g925f\n',
 'samsung galaxy s6 edge unlocked android smartphone (5.1 inch screen, 16mp camera, 32gb, quad-core 2.1ghz, 3gb ram, black (imported from italy)\n',
 'samsung galaxy s6 edge unlocked smartphone 4g (screen: 5.1 inches - 32gb - nano sim card - android lollipop 5) white (imported from europe)\n',
 'samsung s6 edge 32 gb\n',
 'samsung galaxy s6 edge smartphone (5.1 inch touch screen), 32gb memory, android 5.0 white [t-mobile brand]\n',
 'samsung galaxy s6 smartphone (5.1 inches), touch screen, 32gb memory, android 5.0 white [t-mobile brand]\n',
 'samsung galaxy s6 edge unlocked android smartphone 5.1" screen 16mp 32gb quad-core 2.1ghz 3gb ram gold\n',
 'motorola moto g62 5g 6.5" fhd+ 6/128gb grey\n',
 'samsung sm-m536 galaxy m55 dual sim 5g 8gb ram 128gb green eu\n',
 'samsung galaxy s7 edge unlocked smartphone 5.5 inches (android 6.0, dual edge super amoled display, 12mp rear camera and front 5.5 mp, 32 gb) [spanish version: includes pay] gold\n',
 'samsung g935 galaxy s7 smartphone, lte, 5.1" samoled display, 32gb internal memory, 4gb ram, black, tim [italy]\n',
 'galaxy s7 edge smartphone pink\n',
 'sam galaxy a52s ee-128-6-5g-bk | samsung galaxy a52s ds ee 128/6 black\n',
 'samsung galaxy a5 2017 unlocked 4g smartphone (screen: 5.2 inches â€“ 32 gb â€“ nano-sim â€“ android 6.0) blue (european sim card only)\n',
 'samsung sm-g935fzbaitv galaxy s7 edge, 32 gb, blue\n',
 'samsung galaxy xcover 3 ve unlocked smartphone 4g (screen: 4.5 inches â€“ 8 gb â€“ single micro-sim â€“ android) dark silver\n',
 'samsung galaxy s7 edge unlocked smartphone 4g 5.5 inch 32gb 4gb ram android black\n',
 'samsung galaxy s7 edge smartphone (5.5 inches, 32 gb internal memory)\n',
 'samsung sm-a556b galaxy a55 5g dual sim 8gb 128gb awesome navy eu\n',
 'galaxy a55 5g 256gb, handy awesome lemon, android 14.8 gb\n',
 'samsung galaxy s24 smartphone 128gb indigo\n',
 'samsung galaxy a15 4g yellow 128gb\n',
 'samsung galaxy xcover 4 smartphone (5 inch touch screen) 16 gb memory, android 7.0 nougat) black\n',
 'xiaomi redmi note 12 5g 128gb/4gb dual-sim onyx-grey\n',
 'ati xiaomi redmi note 12 pro 5g smartphone, 8gb ram, 128gb rom, midnight black\n',
 'nokia x3 (ovi, ultra-short wave radio, 3.2 mp) mobile phone without contract, branding, unlocked red/black\n',
 'xiaomi smartphone redmi note 13 6.67" 8 gb ram 256 gb black\n',
 'xiaomi poco c65 6gb/128gb purple (purple) dual sim\n',
 'xiaomi smartphone redmi note 13 6.67" 6 gb ram 128 gb blue\n',
 'samsung galaxy s23 smartphone green 6.1" 256gb octa core 8gb ram\n',
 'nokia c21 plus 32gb/2gb ram, dual sim, dark cyan\n',
 'samsung galaxy s8+ mobile phone blue\n',
 'samsung galaxy s8 smartphone, 64 gb, orchid grey, german version (refurbished)\n',
 'samsung galaxy s8+ vodafone\n',
 'samsung 356430 smartphone galaxy s8 (5.8 inch screen) 64 gb, android 7.0 nougat) black\n',
 'samsung galaxy s8 g950f 64g midnight black\n',
 'samsung sm-g950f galaxy s8 64gb midnight black eu\n',
 'samsung galaxy s8 black (midnight black) single sim g950\n',
 'moto g 5âª generaciã³n plus - android 7 free smartphone (5.2 inch trousers, full hd, 4g, 12mp dual pixel, 3gb ram, 32gb, qualcomm snapdragon 2.0ghz), color dorado\n',
 'nokia 6500 classic black on vodafone payg mobile phone black\n',
 'nokia g22 ta-1528 ds 4/64 euro1 blue\n',
 'samsung galaxy a15 5g smartphone 128gb lime\n',
 'samsung galaxy s21 fe 5g, android smartphone, 6.4 zoll dynamic amoled display, 4.500 mah akku, 128 gb/6 gb ram, handy in graphite, inkl. 36 monate manufacturer warranty [exclusive to amazon]\n',
 'samsung galaxy a8 vodafone 0706901 samsung sm.ph.samsung gal a8 black\n',
 'galaxy a8 (2018) dual sim 32gb sm-a530f/ds gold\n',
 'motorola moto x4 32gb black dual sim\n',
 'samsung galaxy note 8 midnight black sm-n950 f italy\n',
 'samsung galaxy s9 64gb (single sim) - carbon black - android 8.0 - international version (refurbished)\n',
 'samsung galaxy s9 smartphone (5.8 inch touch screen, 64gb internal memory, android, dual sim) italian version, midnight black\n',
 'samsung galaxy s9 smartphone (5.8 inch touch screen, 64gb internal memory, android, single sim) midgnight black - german version (refurbished)\n',
 'samsung a920 galaxy a9, smartphone, lte, android 8.0 (oreo), capacity: 512 gb, [italia]\n',
 'samsung galaxy s9 duos sunrise gold [5.8" qhd+ screen] android 8.0, 2.7ghz octa-core 12mp\n',
 'telecom italia spa g960 galaxy s9 smartphone unlocked lte (screen: 5.8 inches â€“ 64 gb â€“ nano-sim â€“ android 8.0 oreo) sunrise gold\n',
 'nokia mã³vil 16argb01a06 8110 dual sim 2.4 inch curva dualcore/4 gb/512mb/2mp wifi radio bluetooth fm 4g black\n',
 'samsung galaxy s9 plus dual sim 64gb sm-g965f/ds midnight black sim free\n',
 'samsung g960 galaxy s9 4g 64gb dual-sim black eu\n',
 'samsung galaxy s9 (5.8", wi-fi, bluetooth 64 gb, 4 gb ram, dual sim, 12 mp, android 8.0), purple - other european version\n',
 'samsung sm-g965fzkavd2 smartphone samsung galaxy s9 plus (6.2 inches, wi-fi, bluetooth 64 gb, 6 gb ram, 12 mp, android 8.0 oreo), black\n',
 'samsung galaxy s9 dual sim 64gb purple â€“ android 8.0 (oreo) â€“ italian version\n',
 'samsung sm-g965fzkdxef smartphone samsung galaxy s9 plus, 6.2 inches, wi-fi, bluetooth 64 gb, 6 gb ram, dual sim, 12 mp, android 8.0 oreo, black â€“ french version\n',
 'samsung sm-s928b galaxy s24 ultra dual sim 5g 12gb ram 512gb titanium grey eu\n',
 'samsung galaxy s23 black 256gb phantom black\n',
 'samsung sm-s901bzwdeuh galaxy s22 128 gb white\n',
 'samsung galaxy note 9 128gb dual sim lavender purple\n',
 'nokia c3-01 touch and type (eu grey)\n',
 'samsung galaxy s10 single sim prism white german version\n',
 'samsung galaxy s23 ultra smartphone lilac 256gb 6.8" octa core\n',
 'motorola razr 40 ultra grey 8/256gb\n',
 'motorola edge40 pro pawe0005se\n',
 'motorola g42-64 go - vert canard\n',
 'xia ds 13 5g 8+256 glo wht\n',
 'samsung sm-a136 galaxy a13 5g 4+64gb 6.5 black ds carrier\n',

In [20]:
image_df.head()
image_df["Mobile_brand"].unique()

array(['Xiaomi', 'Samsung', 'SAMSUNG', 'XIAOMI', 'Nokia', 'Motorola',
       'Smartphone', 'Poco', 'Redmi', 'OnePlus', 'Apple', 'NOKIA', 'POCO',
       'Galaxy', 'Sam', 'ATI', 'Moto', 'Telecom', 'XIA', 'APPLE',
       'iPhone', 'Oneplus', 'Unlocked', 'Free', 'apple', 'SMARTPHONE',
       'M4'], dtype=object)